### PR TITLE
use yml in eslintrc

### PR DESCRIPTION
**Pull request by gaboesquivel**

### CODE REVIEW

**Comment by kevin-wolf** [comment]
@gaboesquivel any reason for using the yaml instead of the regular format? Also, if we use yaml on the `.eslintrc` we *should* be using the file extension (for code formatting, etc).

PS: Why not `.eslintrc.js`? ☺️

**Comment by gaboesquivel** [comment]
readability, json format is for JavaScript interpreters and services communications, yml is more human friendly IMO. Right now is so simple that it almost irrelevant, however if it starts growing, I really think yml is more readable for human beings

**Comment by kevin-wolf** [comment]
Yeah but I'd still prefer the styling for editor formatting and theming.

**Comment by gaboesquivel** [comment]
What Editor are you using that doesn't support yml? it works for me on Atom

**Pull request merged**
